import type { EnemyArchetype, EnemyConfig } from '../../shared/types.ts';

export const BOSS_BEHAVIOR = {
  enrageHpFraction: 0.3,
  enrageSpeedMultiplier: 1.4,
  summonFromWave: 20,
  summonIntervalMs: 8000,
  summonCount: 2
} as const;
export const BONUS_TARGET_HP_PER_WAVE = 0.06;

// Original bestiary of the Gloomtide. No Warcraft references.
export const ENEMIES: Record<EnemyArchetype, EnemyConfig> = {
  thornling: {
    id: 'thornling',
    name: 'Thornling',
    description: 'Basic briar fiend. Balanced.',
    baseHp: 60,
    baseSpeed: 70,
    baseReward: 8,
    livesLost: 1,
    physicalArmor: 0,
    wardArmor: 0,
    regenPerSecond: 0,
    color: 0x7cb342,
    radius: 11,
    isBoss: false,
    isElite: false
  },
  swiftwisp: {
    id: 'swiftwisp',
    name: 'Swiftwisp',
    description: 'Fragile but very fast spark-fae.',
    baseHp: 32,
    baseSpeed: 125,
    baseReward: 7,
    livesLost: 1,
    physicalArmor: 0,
    wardArmor: 0,
    regenPerSecond: 0,
    color: 0x26c6da,
    radius: 9,
    isBoss: false,
    isElite: false
  },
  cragback: {
    id: 'cragback',
    name: 'Cragback',
    description: 'Slow living boulder. Huge HP.',
    baseHp: 260,
    baseSpeed: 48,
    baseReward: 16,
    livesLost: 2,
    physicalArmor: 0.1,
    wardArmor: 0,
    regenPerSecond: 0,
    color: 0x8d6e63,
    radius: 14,
    isBoss: false,
    isElite: true
  },
  ironbark: {
    id: 'ironbark',
    name: 'Ironbark Sentinel',
    description: 'Plated husk. Resists physical & siege.',
    baseHp: 150,
    baseSpeed: 62,
    baseReward: 12,
    livesLost: 1,
    physicalArmor: 0.55,
    wardArmor: 0,
    regenPerSecond: 0,
    color: 0x90a4ae,
    radius: 11,
    isBoss: false,
    isElite: false
  },
  runescale: {
    id: 'runescale',
    name: 'Runescale Drake',
    description: 'Warded scales shrug off magic.',
    baseHp: 150,
    baseSpeed: 66,
    baseReward: 12,
    livesLost: 1,
    physicalArmor: 0,
    wardArmor: 0.55,
    regenPerSecond: 0,
    color: 0x5c6bc0,
    radius: 11,
    isBoss: false,
    isElite: false
  },
  mossmaw: {
    id: 'mossmaw',
    name: 'Mossmaw',
    description: 'Regenerates wounds over time.',
    baseHp: 130,
    baseSpeed: 60,
    baseReward: 11,
    livesLost: 1,
    physicalArmor: 0,
    wardArmor: 0,
    regenPerSecond: 6,
    color: 0x558b2f,
    radius: 11,
    isBoss: false,
    isElite: false
  },
  gloomite: {
    id: 'gloomite',
    name: 'Gloom Mite',
    description: 'Weak alone, deadly in swarms.',
    baseHp: 22,
    baseSpeed: 85,
    baseReward: 3,
    livesLost: 1,
    physicalArmor: 0,
    wardArmor: 0,
    regenPerSecond: 0,
    color: 0x6a1b9a,
    radius: 7,
    isBoss: false,
    isElite: false
  },
  warlord: {
    id: 'warlord',
    name: 'The Hollow Warden',
    description: 'Boss. Enrages, hardens, and calls mites.',
    baseHp: 2200,
    baseSpeed: 52,
    baseReward: 150,
    livesLost: 5,
    physicalArmor: 0.15,
    wardArmor: 0.15,
    regenPerSecond: 10,
    color: 0xd32f2f,
    radius: 18,
    isBoss: true,
    isElite: true
  },
  pilferer: {
    id: 'pilferer',
    name: 'Gilded Pilferer',
    description: 'Bonus imp. Catch it for a fortune!',
    baseHp: 400,
    baseSpeed: 95,
    baseReward: 250,
    livesLost: 0,
    physicalArmor: 0,
    wardArmor: 0,
    regenPerSecond: 0,
    color: 0xffd700,
    radius: 10,
    isBoss: false,
    isElite: true
  }
};
